# Generated by Django 6.0.2 on 2026-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name_patronymic', models.CharField(max_length=200, verbose_name='Имя и отчество')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Личный телефон')),
                ('work_phone', models.CharField(max_length=20, verbose_name='Рабочий телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name_patronymic'],
            },
        ),
    ]
