# Generated by Django 6.0.2 on 2026-04-24 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('product_group', models.CharField(max_length=100, verbose_name='Группа товара')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена закупки')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Скидка (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exported', models.BooleanField(default=False, verbose_name='Выгружен')),
            ],
            options={
                'verbose_name': 'Запись продажи',
                'verbose_name_plural': 'Записи продаж',
                'ordering': ['-created_at'],
            },
        ),
    ]
