# Generated by Django 6.0.2 on 2026-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_number', models.IntegerField(verbose_name='Номер датчика')),
                ('location', models.CharField(max_length=200, verbose_name='Место расположения')),
                ('zone', models.IntegerField(verbose_name='Номер зоны (сектора)')),
                ('reading_time', models.DateTimeField(verbose_name='Дата и время показания')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Температура (°C)')),
                ('exported', models.BooleanField(default=False, verbose_name='Выгружен')),
            ],
            options={
                'verbose_name': 'Показание датчика',
                'verbose_name_plural': 'Показания датчиков',
                'ordering': ['-reading_time'],
            },
        ),
    ]
