# Generated by Django 6.0.2 on 2026-04-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование статьи')),
            ],
            options={
                'verbose_name': 'Статья издержек',
                'verbose_name_plural': 'Статьи издержек',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (руб.)')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Назначение')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='staff.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Подотчётная сумма',
                'verbose_name_plural': 'Подотчётные суммы',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (руб.)')),
                ('expense_date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='lab10.expensecategory', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Издержка',
                'verbose_name_plural': 'Издержки',
                'ordering': ['-expense_date'],
            },
        ),
    ]
