# Generated by Django 6.0.2 on 2026-03-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Температура', max_length=200, verbose_name='Название параметра')),
                ('unit', models.CharField(default='°C', max_length=50, verbose_name='Единица измерения')),
                ('min_value', models.FloatField(default=10.0, verbose_name='Минимум допустимого диапазона')),
                ('max_value', models.FloatField(default=40.0, verbose_name='Максимум допустимого диапазона')),
                ('warning_percent', models.FloatField(default=15.0, verbose_name='Порог предупреждения (%)')),
                ('history_count', models.IntegerField(default=10, verbose_name='Количество предыдущих значений (N1)')),
            ],
            options={
                'verbose_name': 'Конфигурация датчика',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensorconfig')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-timestamp'],
            },
        ),
    ]
