# Generated by Django 6.0.2 on 2026-04-24 22:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Например: Toyota Camry, LADA Vesta', max_length=100, verbose_name='Марка автомобиля')),
                ('state_number', models.CharField(help_text='Например: А123БВ777', max_length=20, unique=True, verbose_name='Гос. номер')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска')),
                ('fuel_norm', models.DecimalField(decimal_places=3, help_text='Средний расход топлива в литрах на 1 км', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Норма расхода (л/км)')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['make', 'state_number'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.automobile', verbose_name='Закреплённый автомобиль')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='staff.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время выезда')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время заезда')),
                ('start_mileage', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Начальный километраж (км)')),
                ('end_mileage', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Конечный километраж (км)')),
                ('mileage', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Пробег (км)')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Расход топлива (л)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('automobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='transport.automobile', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='transport.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-departure_time'],
            },
        ),
    ]
