# Generated by Django 6.0.2 on 2026-04-24 22:58

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, default='', help_text='10 цифр (организация) или 12 цифр (физ. лицо). Необязательно.', max_length=12, validators=[sales.models.validate_inn], verbose_name='ИНН'),
        ),
    ]
